version: '3'

services:
  frontend:
    command: npm run serve
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
  backend:
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src