version: '3'

services:
  frontend:
    build: ./frontend
    container_name: shopping-docker-frontend
    command: npm run serve
#    command: serve -s build -l 3000
    ports:
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true
#    volumes:
#      - ./frontend/src:/usr/src/app/src

  backend:
    build: ./backend
    container_name: shopping-docker-backend
    command: npm run start
    restart: unless-stopped
    ports:
        - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://mevn-shopping-list-docker.com
      - MONGO_URL=mongodb://backend_db:27017/api
    depends_on:
      - backend_db

  backend_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api: